apiVersion: v1
kind: Service
metadata:
  name: mediawiki-app
  labels:
{{ include "mediawiki.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mediawiki-app
    app.kubernetes.io/instance: {{ .Release.Name }}
